### ISSUE TITLE
Crash in MutableLiveQueue

### ISSUE THREAD

**Issue by kapilsukhyani** [spotify/mobius#129]
There is crash in MutableLiveQueue, please look at the stack trace below

java.lang.NullPointerException: Attempt to invoke interface method 'void androidx.lifecycle.Observer.onChanged(java.lang.Object)' on a null object reference
    at com.spotify.mobius.android.MutableLiveQueue.lambda$post$0(MutableLiveQueue.java:124)
    at com.spotify.mobius.android.-$$Lambda$MutableLiveQueue$vOf0H-vBAqo2vnbWBOWfiBCGWLc.run
    at android.os.Handler.handleCallback(Handler.java:873)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:198)
    at android.app.ActivityThread.main(ActivityThread.java:6732)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by milchopenchev** [comment]
Hi, thank you for the report, I've opened a PR to address this issue here: https://github.com/spotify/mobius/pull/130

**Comment by kapilsukhyani** [comment]
Thanks for putting up the PR

**Comment by milchopenchev** [comment]
Hi sorry for delayed response, but the fix for this has been merged, and should be available in the next release of the library.

**Comment by milchopenchev** [comment]
Hi @kapilsukhyani - I just noticed this issue is still open. Can you confirm that the fix that was merged has addressed your issue so we can close this?

**Comment by kapilsukhyani** [comment]
Hey @milchopenchev , we just have consumed the fix, will see if we get any reports of this issue and if not I will update here again for you to close the issue.

Thanks!
